import { useEffect, useState } from 'react';
import { AlertCircle, BookOpenCheck, CheckCircle2, RefreshCw } from 'lucide-react';
import api from '../../services/api';

const selectClass = 'w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm text-white focus:border-sky-500 focus:outline-none focus:ring-1 focus:ring-sky-500';

export default function CourseEnrollmentForm() {
  const [students, setStudents] = useState([]); const [courses, setCourses] = useState([]); const [selectedStudent, setSelectedStudent] = useState(''); const [selectedCourse, setSelectedCourse] = useState(''); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [message, setMessage] = useState(null);
  const fetchOptions = async () => { setLoading(true); try { const [studentResponse, courseResponse] = await Promise.all([api.get('/admin/users', { params: { role: 'student' } }), api.get('/admin/courses')]); setStudents(studentResponse.data?.data || []); setCourses(courseResponse.data?.data || []); } catch (error) { setMessage({ type: 'error', text: error.response?.data?.message || 'Could not load students and courses. Refresh and try again.' }); } finally { setLoading(false); } };
  useEffect(() => { const timer = window.setTimeout(() => { fetchOptions(); }, 0); return () => window.clearTimeout(timer); }, []);
  const submit = async (event) => { event.preventDefault(); if (!selectedStudent || !selectedCourse) { setMessage({ type: 'error', text: 'Select both a student and a course before enrolling.' }); return; } setSubmitting(true); setMessage(null); try { const { data } = await api.post('/admin/enroll', { studentId: selectedStudent, courseId: selectedCourse }); setMessage({ type: 'success', text: data.message || 'Student enrolled successfully.' }); setSelectedStudent(''); setSelectedCourse(''); await fetchOptions(); } catch (error) { setMessage({ type: 'error', text: error.response?.data?.message || 'Enrollment could not be completed.' }); } finally { setSubmitting(false); } };
  return <div className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900 shadow-xl shadow-slate-950/20"><div className="flex items-center justify-between gap-4 border-b border-slate-800 px-6 py-5"><div className="flex items-center gap-3"><div className="rounded-xl bg-violet-500/10 p-2.5 text-violet-400"><BookOpenCheck className="h-5 w-5" /></div><div><h2 className="font-bold text-white">Course enrollment</h2><p className="mt-0.5 text-xs text-slate-400">Add a student to a course while respecting seat capacity.</p></div></div><button type="button" onClick={fetchOptions} disabled={loading || submitting} className="rounded-lg p-2 text-slate-400 transition hover:bg-slate-800 hover:text-white disabled:opacity-50" aria-label="Refresh lists"><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} /></button></div><form onSubmit={submit} className="space-y-5 p-6">{message && <Notice message={message} />}{loading ? <div className="flex items-center justify-center gap-2 py-12 text-sm text-slate-400"><span className="h-4 w-4 animate-spin rounded-full border-2 border-sky-400 border-t-transparent" />Loading enrollment options…</div> : <><div><label className="mb-2 block text-sm font-medium text-slate-300">Student</label><select required value={selectedStudent} onChange={(e) => setSelectedStudent(e.target.value)} className={selectClass}><option value="">Choose a student</option>{students.map((student) => <option key={student._id} value={student._id}>{student.name} — {student.rollNumber || student.email} (Semester {student.semester || '—'})</option>)}</select>{students.length === 0 && <p className="mt-2 text-xs text-amber-400">No student accounts are available yet. Create one in User provisioning.</p>}</div><div><label className="mb-2 block text-sm font-medium text-slate-300">Course</label><select required value={selectedCourse} onChange={(e) => setSelectedCourse(e.target.value)} className={selectClass}><option value="">Choose a course</option>{courses.map((course) => { const count = course.students?.length || 0; const full = count >= course.maxStudents; return <option key={course._id} value={course._id} disabled={full}>[{course.courseCode}] {course.title} — {count}/{course.maxStudents} seats{full ? ' (full)' : ''}</option>; })}</select>{courses.length === 0 && <p className="mt-2 text-xs text-amber-400">No courses are available yet. Create a course from the Course Directory.</p>}</div><button disabled={submitting || students.length === 0 || courses.length === 0} className="flex w-full items-center justify-center gap-2 rounded-xl bg-sky-600 px-4 py-3 text-sm font-semibold text-white transition hover:bg-sky-500 disabled:cursor-not-allowed disabled:opacity-60"><BookOpenCheck className="h-4 w-4" />{submitting ? 'Enrolling student…' : 'Enroll student'}</button></>}</form></div>;
}
function Notice({ message }) { const good = message.type === 'success'; return <div role="alert" className={`flex gap-2 rounded-xl border p-3 text-sm ${good ? 'border-emerald-500/30 bg-emerald-500/10 text-emerald-300' : 'border-rose-500/30 bg-rose-500/10 text-rose-300'}`}>{good ? <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0" /> : <AlertCircle className="mt-0.5 h-4 w-4 shrink-0" />}<span>{message.text}</span></div>; }
